CREATE DATABASE db_learn IF NOT EXIST;
CREATE USER learn WITH ENCRYPTED PASSWORD 'learn123';
GRANT ALL PRIVILEGES ON DATABASE db_learn TO learn;
GRANT CONNECT ON DATABASE db_learn TO learn;
ALTER USER learn WITH SUPERUSER