version: '3.8'
services:

    learn-postgres:
        image: postgres:13.2-alpine
        container_name: learn-postgres
        ports:
            - 5440:5432
        volumes:
            - ./docker/postgres:/docker-entrypoint-initdb.d
            - pg-data:/var/lib/postgresql/data
        env_file:
            - ./env_file/postgres.env
        
volumes:
    pg-data: